### ISSUE TITLE
Formatting not working (on linux)

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-vscode#102]
Reported by @fvictorio on linux. Nothing in the output channel to suggest why. Extension picked as the formatter.

**Comment by adriandelgg** [comment]
I'm on Linux and can confirm formatting is not working.

**Comment by kanej** [comment]
@adriandelgg I have been trying to reproduce this, and see formatting working on ubuntu. Could you send us the vscode version info by going to `help -> about` and click the copy button on the dialog?

**Comment by adriandelgg** [comment]
> @adriandelgg we debugged the linux install that had formatting as failing. The user had flipped a setting that turned off formatting.
> 
> Can you confirm, that under `settings -> hardhat -> Solidity:Formatter`, it is set to `prettier` and not `none`?
> 
> ![image](https://user-images.githubusercontent.com/24030/158851673-d7903642-78c3-42ae-a81d-90bfbf5ca9e1.png)
> 
> 
> 
> 

Yes, I did that and it still wasn't working.

**Comment by Soohan-Park** [comment]
Me either. it doesn't work on Ubuntu..!

**Comment by kanej** [comment]
> Me either. it doesn't work on Ubuntu..!

Hey, do you have a `.prettierrc` of some form? Could you post it?

**Comment by adriandelgg** [comment]
On Linux, it also doesn't show the option for selecting the formatter.

Node Version: 16.14.2
OS: Linux
Distro: openSUSE Tumbleweed 15.3
Extension Version: 0.2.2
VS Code Version: 1.66.0

See here, this is all that shows for the Hardhat Extension Settings:
![2022-04-06_18-17](https://user-images.githubusercontent.com/32179921/162100800-4b022204-1a20-4685-b492-ff674b9996ce.png)

**Comment by kanej** [comment]
> On Linux, it also doesn't show the option for selecting the formatter.
> 
> Is there something else that needs to be installed along with the Hardhat extension in order for it to work properly?
> 
> Node Version: 16.14.2 OS: Linux Distro: openSUSE Tumbleweed 15.3 Extension Version: 0.2.2 VS Code Version: 1.66.0
> 
> See here, this is all that shows for the Hardhat Extension Settings: ![2022-04-06_18-17](https://user-images.githubusercontent.com/32179921/162100800-4b022204-1a20-4685-b492-ff674b9996ce.png)

Hey @adriandelgg, we have removed that formatting setting (it only added to confusion). I haven't been able to get to the bottom of what is happening on some linux install for the formatting. The last release enhanced the logging to the output channel around formatting.

Could you force a document format with the solidity extension (right click in a sol file and format with), then check the output channel for hardhat?

**Comment by adriandelgg** [comment]
Hi @kanej,
I was able to identify the problem. My `settings.json` was showing the wrong formatter due to me migrating from Juan Blanco's Solidity extension to Hardhat's. This is what it had:
```json
"[solidity]": {
  "editor.defaultFormatter": "JuanBlanco.solidity"
}
```

I updated it to this and the formatting worked
```json
"[solidity]": {
  "editor.defaultFormatter": "NomicFoundation.hardhat-solidity"
}
```

I think the issue might be that Hardhat isn't able to overwrite this setting if it's already present in the `settings.json`?

Things like this would be useful to include in the `README.md` in a troubleshooting section.

**Comment by kanej** [comment]
@adriandelgg agreed. I think people are having problems getting the formatter configured, but that the answer is better documentation on the readme to walk people through both setup and troubleshooting, the people moving from `JuanBlanco.solidity` to `NomicFoundation.hardhat-solidity` already having formatting configured is a great point.

As of right now I am not aware of any linux specific issues with formatting, or non-setup and config related issues with formatting. I am going to close this issue in preference to @adriandelgg suggested #159 improvements to the readme.
