### ISSUE TITLE
Autocompletion not working properly on arrays

### ISSUE THREAD

**Issue by 0xSkly** [NomicFoundation/hardhat-vscode#108]
Autocompletion of arrays does not work as expected. For storage arrays, there are no array functions like `push`.  Also on the array variable, it gives you autocompletion as if its the type itself instead of an array of the type. works better for mappings
![autocompletion issue](https://user-images.githubusercontent.com/91403802/157914541-7da3309a-52ee-45de-93d9-f4b9505db494.gif)

**Comment by kanej** [comment]
Array completions where added with https://github.com/NomicFoundation/hardhat-vscode/pull/180.
