### ISSUE TITLE
no validation if hh error in other file

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-vscode#177]
A hardhat error in a different file from the active editor file stops validation warnings/errors from coming through.

The validation process throws an error because of a different file. Only one error is returned, but it is not shown because it is not on the active editor file.

Some questions to answer:
* it appears that files that are not in the dependency graph can still block if they have an error, that is not expected
* can we expend hh code to give all errors not just one

**Comment by kanej** [comment]
We now display a warning against the solidity status if the validation is being blocked by import errors in another file.

**Comment by envatic** [comment]
I think this should not be case . since the whole extension is now turned off and stops linting,  and the error is not helpful as well since we can know which file is failing.

**Comment by kanej** [comment]
> I think this should not be case . since the whole extension is now turned off and stops linting, and the error is not helpful as well since we can know which file is failing.

Hi @envatic, thanks for the feedback.

Just so I am understanding correctly, the problem you are raising is: if validation fails because of an error in a dependent file, the validation error message in the status bar isn't helpful as it doesn't tell you where the actual source of the error is?
