### ISSUE TITLE
Lint error still appear after fixed code

### ISSUE THREAD

**Issue by huypn** [NomicFoundation/hardhat-vscode#207]
Please check video for more detail

https://user-images.githubusercontent.com/1724061/177193328-f5fc41b8-e45d-4751-b2e2-98842cbf4f7e.mp4

Thanks!

**Comment by kanej** [comment]
@huypn thanks for the video, it really helps. Is the repo you were using open source to help with reproducing?

**Comment by grapevinegizmos** [comment]
I am having the same problem.  Getting squigglys on codes that is revised and fixed.  Have to "Reload Windows" to make force a recheck and make it go away.

**Comment by Cue972** [comment]
I have the same error. I uninstalled the extension until it's fixed

**Comment by arjun-io** [comment]
This appears to be fixed for me after upgrading to 0.4.4

**Comment by kanej** [comment]
@huypn are you still seeing this issue in the latest release?

**Comment by arjun-io** [comment]
0.4.4 fixed this issue for me, but it seems that 0.4.5 re-introduced it.

**Comment by arjun-io** [comment]
@kanej I added you to a repo (private for now, could only reproduce based on some our internal project setup) which reproduces this behavior, I believe it's related to file size but not positive: https://github.com/arjun-io/hardhat-solidity-test

**Comment by marcusnewton** [comment]
I am also getting stale lint errors for version 0.4.5.

**Comment by kanej** [comment]
> @kanej I added you to a repo (private for now, could only reproduce based on our internal project setup) which reproduces this behavior, I believe it's related to file size but not positive: https://github.com/arjun-io/hardhat-solidity-test
> 
> edit: To answer your questions, no validation job errors, yes the files compile

That is brilliant, thanks. I'll take a look.

**Comment by kanej** [comment]
@arjun-io I debugged through your reproduction repo and found the issue that is causing the repo to not clear warnings/errors in the editor. I another issue (#221) for it, in case there are more bugs that can cause `Lint error still appear after fixed code`.

I have put together a fix for #221 issue in this PR (#222), that we will look to get rolled out with the next release.

**Comment by huypn** [comment]
Hi @kanej : I just tried to install v0.4.6 and lint errors seem not work. Please check image.
![image](https://user-images.githubusercontent.com/1724061/183960754-4d1e183b-6fe1-4bf4-8f94-f1e714a23056.png)

**Comment by kanej** [comment]
> Hi @kanej : I just tried to install v0.4.6 and lint errors seem not work. Please check image. ![image](https://user-images.githubusercontent.com/1724061/183960754-4d1e183b-6fe1-4bf4-8f94-f1e714a23056.png)
> 
> I tried to remove ; for 2 lines: 37, 38 but I don't see any errors notification.

Hey @huypn, is there any information reported against `solidity` on the status bar if you click on the curly braces?

![image](https://user-images.githubusercontent.com/24030/183975037-4b6f24bc-0dd5-48c1-a29a-29882c40ddd6.png)

**Comment by kanej** [comment]
> Sorry @kanej, I don't know why, but it's good working now. But it's still not disappear after fixed error.
> 
> ![image](https://user-images.githubusercontent.com/1724061/183976374-6bc4a2a4-21a9-4e10-be17-f2b5b667007f.png)

Hey, @huypn, we have just released `v0.5.0` which includes a fix for the diagnostic (the inline warning/error) not disappearing, at least in some cases.

Can you confirm whether you encounter diagnostics not clearing up in `v0.5.0`?

**Comment by huypn** [comment]
https://user-images.githubusercontent.com/1724061/184126684-c6375b23-ac2d-4e08-952e-753fff5db201.mp4

Hi @kanej , it's good working now.
Thank you so much!

**Comment by kanej** [comment]
Brilliant. Thanks for the help @huypn, it is deeply appreciated!

I am going to close this issue as currently I don't know of any other cases of validation warnings/errors persisting.
