### ISSUE TITLE
GitPod compatibility

### ISSUE THREAD

**Issue by storm1er** [NomicFoundation/hardhat-vscode#208]
Hi everyone,

Explicit title: is there any plan to make this extension compatible with gitpod? (vscode online, linked to repo, very useful for contributors)

Thanks =)

**Comment by alcuadrado** [comment]
Yes, we have plans to make both the extension and the language server in other environments.

These are mid-term plans, so I don't think we'll work on them in the next 2-3 months, unfortunately. If this changes (e.g. because we hire more people or priorities change), I'll update this issue.

**Comment by kanej** [comment]
One option to speed up support for vscode for web (and gitpod with it), would be to split syntax highlighting and maybe navigation from the compiler validation and warnings.

The barrier to running as a web extension is our access of the file system and those are mainly to support validation via solc (and hardhat dependency resolution). Navigation is based off of a `solidity-parser` parse, so we may be able to provide this in a pure browser setting.

**Comment by Janther** [comment]
Could be worth to evaluate having extension packs one with all the web-only functionalities and another with everything.

**Comment by Janther** [comment]
By the way I installed the `vsix` file in Gitpod and everything runs beautifully, even navigation. I believe the file system bits are seamlessly run on the Gitpod ephemeral server via SSH. I did not test much though.

**Comment by Janther** [comment]
Sorry about that, clicking on open hardhat configuration fails

<img width="500" alt="Screen Shot 2022-08-09 at 9 57 22 PM" src="https://user-images.githubusercontent.com/1022054/183620896-a6c09f5e-48c5-484e-8494-75f229d8879f.png">

**Comment by kanej** [comment]
Oh that is interesting. I suspect the nav to `hardhat.config.ts` file is a separate bug, maybe some assumptions about file paths that don't hold on the web host.

I have opened an issue for that (as separate from gitpod support): https://github.com/NomicFoundation/hardhat-vscode/issues/227

**Comment by kanej** [comment]
@Janther I had assumed that gitpod wasn't showing our extension because we are not a `webextension`, but if your able to install via vsix, it means they are running vscode extensions partially on the backend (which is all hardhat-vscode needs to run).

Let me dig a bit further and see why we are not appearing in the extensions tab when clearly the plugin can run.

**Comment by Janther** [comment]
Gitpod has its own registry for extensions because vscode is Microsoft and doesn't want to share extensions with 3rd party implementations of the editor.

**Comment by kanej** [comment]
@Janther we have added `hardhat-vscode` to openvsx (`v0.4.6`), I have been able to install the extension (and use it) via gitpod's web-based vscode:

![image](https://user-images.githubusercontent.com/24030/183745467-9a847481-48dd-4cdf-a437-0e50aa1ae173.png)

**Comment by kanej** [comment]
Reviews on openvsx welcome!

**Comment by Janther** [comment]
Don't forget to add to your workflow the publishing of new versions to both registries now so there will be consistency in the environments ;)

**Comment by kanej** [comment]
> Don't forget to add to your workflow the publishing of new versions to both registries now so there will be consistency in the environments ;)

Ha, I am updating our release docs as we speak!

**Comment by kanej** [comment]
The extension is available in gitpod via the openvsx registry: https://open-vsx.org/extension/NomicFoundation/hardhat-solidity
