### ISSUE TITLE
High cpu usage in VSCODE with the plugin "Solidity + Hardhat v0.4.4"

### ISSUE THREAD

**Issue by turgaycabalak** [NomicFoundation/hardhat-vscode#214]
Hi everyone.

Nowadays I realized that my cpu usage increased once the hardhat plugin is active in VSCODE.  And also  a blue loading circle near my mouse icon won't disappear unless I disable the plugin in VSCODE. Whenever I disable it, cpu usage goes down. 

I checked the "Process" in "Task Manager" and realized that "Microsoft Defender Antivirus Service" is the first one which uses the cpu the most.

For now I keep the plugin disabled unless I am not using it. But it is awkward.

**Comment by alcuadrado** [comment]
Thanks for creating this issue, @turgaycabalak! I transferred it to the `NomicFoundation/hardhat-vscode`.

**Comment by kanej** [comment]
@turgaycabalak thanks for that, the feedback is much appreciated. We have pushed a fix for some cases of high cpu: https://github.com/NomicFoundation/hardhat-vscode/pull/212

It is release as `0.4.5` on the marketplace now: https://marketplace.visualstudio.com/items/NomicFoundation.hardhat-solidity/changelog

Could you try it and see if you are still getting high cpu. If you do still see it, can you send another image of the output but scrolled to the bottom?

**Comment by turgaycabalak** [comment]
Problem seems solved. Thank you very much. Appreciated.

**Comment by 0xMohandes** [comment]
Thanks. Tried the new version. Looks like it's fixed.

**Comment by kanej** [comment]
> Problem seems solved. Thank you very much. Appreciated.

@turgaycabalak brilliant. Glad this resolved the issue. Would you mind updating your review on the marketplace to avoid new users thinking this is a current bug?

**Comment by turgaycabalak** [comment]
> > Problem seems solved. Thank you very much. Appreciated.
> 
> @turgaycabalak brilliant. Glad this resolved the issue. Would you mind updating your review on the marketplace to avoid new users thinking this is a current bug?

I did :) Thank you.
