### ISSUE TITLE
Missing Solidity Code Compilation and other important features

### ISSUE THREAD

**Issue by agrawalmitesh** [NomicFoundation/hardhat-vscode#215]
This extension it is missing a very important feature of **compiling** the contract. That feature is being provided by VSCode "solidity" extension, but we need to disable that to make this extension work. Either collaborate with that extension so that we can use both the extensions or provide all the features supported by it as listed below

- Syntax highlighting
- Snippets
- Compilation of the current contract
- Compilation of all the contracts
- Code completion for all contracts / libraries in the current file and all referenced imports
- Default project structure (solidity files needs to be in the src/ directory, and libraries in the lib/ directory). Libraries will follow the same structure.
- Support for different solidity versions (Remote and local)
- Linting using [Solhint](https://github.com/protofire/solhint) or [Ethlint](https://github.com/duaraghav8/Ethlint)

**Comment by kanej** [comment]
Hey @agrawalmitesh, thanks for the feedback.

Are you trying to compile contracts within a hardhat project or do you mean solidity files by themselves or outside a hardhat project?

If the plugin detects a hardhat configuration file, it will provide inline compilation warnings/errors. To get the compilation output you would run `npx hardhat compile` in the root of the project at the terminal.

Have I captured what you want to do, or am I misunderstanding?

**Comment by antico5** [comment]
I'm closing this issue since all enumerated points are implemented (for compilation there's a  task + command), and for linting support there's issue #39 opened. Feel free to open a new issue with other particular feature requests.
