### ISSUE TITLE
Quick fix: import missing contract

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-vscode#244]
Respond to a missing contract/function by auti-importing the sol file containing the contract. Something like typescripts auto-import functionality.

Doing this in general would be the ideal. But there may be ways of breaking down the task that deliver a big chunk of value (i.e. autoimport of `console.log` from hardhat).

**Comment by fvictorio** [comment]
+1 at having just autoimport of `console.log` to begin with! It shouldn't be too hard (:tm:) and it would be super useful.

**Comment by kanej** [comment]
I suspect we should split this one into two, pulling in hardhat `console.log` to build up more knowledge of how easy these are, and another for the typescript level "import anything".
