### ISSUE TITLE
Validation blocked - no compatible solc version found

### ISSUE THREAD

**Issue by joWexler** [NomicFoundation/hardhat-vscode#245]
Hi! I've been using `Solidity + Hardhat`. Formatting works fine, however any kind of validation is not working because of the following error:
![Screenshot from 2022-08-31 23-41-06](https://user-images.githubusercontent.com/111702507/187777705-8fc1eaa3-6ac5-4787-a53e-1ace9397fa71.png)

It's pretty annoying, I tested it on all versions starting from 0.4.4 to 0.5.1 on Arch linux running VSCodium. I also ran a virtual machine on ubuntu22 with deb `vscode` package and got the same result.

Thank you!
**OS**: Arch
**VSCode version**: VSCodium

**Comment by joWexler** [comment]
It crashes in any project, so I don't think there's a need provide link for my repository

**Comment by joWexler** [comment]
**Hardhat version**: 2.10.2

**Comment by alcuadrado** [comment]
Does hardhat compile your project correctly?

**Comment by joWexler** [comment]
> Does hardhat compile your project correctly?

I've just compiled my project, it looks this way now:
![Screenshot from 2022-09-01 00-38-05](https://user-images.githubusercontent.com/111702507/187789865-8ed088c2-bfdb-4b6c-af12-7e33c77e741a.png)

**Comment by joWexler** [comment]
I've just done a little of debugging, it seems to be working with projects that don't use .env file despite vscodium and os. I import it using `. ./.env` in the console command which is quite unconventional, so I tried using `dotenv` package instead, not it works flowlessly. It seems that Hardhat plugin just couldn't resolve environmental variables so couldn't open hardhat.config.

Thanks @alcuadrado for tip!
