### ISSUE TITLE
Validation blocked - Missing task argument

### ISSUE THREAD

**Issue by Usman15B** [NomicFoundation/hardhat-vscode#264]
I am facing this issue as code completion not working.

![Screenshot 2022-09-25 161209](https://user-images.githubusercontent.com/40345776/192140634-27fbae80-97c2-4472-ba82-d5b6546ac489.png)

![Screenshot 2022-09-25 171040](https://user-images.githubusercontent.com/40345776/192142739-599f29a3-ae8b-47a0-961d-a16909ea4720.png)

**Comment by kanej** [comment]
Hello @Usman15B, I suspect this is the same as this bug: https://github.com/NomicFoundation/hardhat-vscode/issues/255

We have a PR in review that will more feedback as to what is going wrong.

Can you confirm that the `solidity` file you want validation on is outside of a `./contracts` folder but within a `Hardhat` project?

**Comment by Usman15B** [comment]
No its a simple hardhat sample project.

**Comment by kanej** [comment]
I have been able to reproduce the error on windows with a new hh project with hh `v2.11.2`

**Comment by Usman15B** [comment]
Perfect. Thanks!
