### ISSUE TITLE
Validation blockedCannot find module '@nomicfoundation/solidity-analyzer-darwin-arm64'

### ISSUE THREAD

**Issue by bijianing97** [NomicFoundation/hardhat-vscode#271]
Cannot find module '@nomicfoundation/solidity-analyzer-darwin-arm64' Require stack:

/Users/sspin/myproject/solidity/prison_test/node_modules/hardhat/node_modules/@nomicfoundation/solidity-analyzer/index.js
/Users/sspin/myproject/solidity/prison_test/node_modules/hardhat/internal/solidity/parse.js
/Users/sspin/myproject/solidity/prison_test/node_modules/hardhat/builtin-tasks/compile.js
/Users/sspin/myproject/solidity/prison_test/node_modules/hardhat/internal/core/tasks/builtin-tasks.js
/Users/sspin/myproject/solidity/prison_test/node_modules/hardhat/internal/core/config/config-loading.js
/Users/sspin/myproject/solidity/prison_test/node_modules/hardhat/register.js
/Users/sspin/.vscode/extensions/nomicfoundation.hardhat-solidity-0.5.5/server/out/worker.js

my computer is mac m2 monterey 12.6
node v14.19.3
hardhat-vscode is v0.5.5

hardhat.config.ts
```ts
const config: HardhatUserConfig = {
  solidity: "0.8.4",
  networks: {
    "local-test": {
      url: "http://localhost:42000",
      accounts: batchImportPrivateKey(),
    },
  },
  gasReporter: {
    enabled: process.env.REPORT_GAS !== undefined,
    currency: "USD",
  },
  etherscan: {
    apiKey: process.env.ETHERSCAN_API_KEY,
  },
};
```

So what's wrong with it?

**Comment by bijianing97** [comment]
sorry guys, I miss SPDX-License-Identifier at the beginning, do not mind it

**Comment by antico5** [comment]
Hi! the SPDX License identifier is not related to the original error. Probably what happened is that you had an older version of the extension (because the `Cannot find module solidity-analyzer` was an issue on a previous version). On the latest release, 0.5.5, you shouldn't have that problem anymore but let us know
