### ISSUE TITLE
Error: Unable to initialize Hardhat Runtime Environment

### ISSUE THREAD

**Issue by joejordan** [NomicFoundation/hardhat-vscode#274]
Using the latest version (0.5.5) of the plugin on VSCode v1.72.2, I am receiving the below error after the IDE starts up. I am not receiving any linting information from the plugin, but other features like import autocomplete are still working.

I enabled verbose mode and it indexed all the solidity files in the project before the below error displayed.

```
Error: Unable to initialize Hardhat Runtime Environment
    at initialiseWorkerState (c:\Users\Joe\.vscode\extensions\nomicfoundation.hardhat-solidity-0.5.5\server\out\worker.js:1:15983)
    at initialiseWorker (c:\Users\Joe\.vscode\extensions\nomicfoundation.hardhat-solidity-0.5.5\server\out\worker.js:1:17449)
    at Object.<anonymous> (c:\Users\Joe\.vscode\extensions\nomicfoundation.hardhat-solidity-0.5.5\server\out\worker.js:1:17793)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by antico5** [comment]
@joejordan Hi! normally this can happen due to one of the following reasons:
- 1) you are not on a hardhat project
- 2) node modules are not installed
- 3) loading the hardhat config fails

The loading process can be a bit fragile because it uses the local installation of hardhat to perform compilation (i.e. linting, compiler errors). To detect what's happening on your end, please run `npx hardhat compile` on your project and see if it works. It can give a hint on what's failing.

**Comment by joejordan** [comment]
Ah, my mistake was assuming that having the plugin installed and editing `.sol` files would be sufficient to get it to work, similar to Juan Blanco's plugin. Maybe the title of the plugin, _Hardhat for Visual Studio Code_ should have been enough to tell me that I would need an installation of Hardhat to get this working.

FYI after adding hardhat to my package.json, `npx hardhat compile` instigates the "Create a Hardhat Project" as I would expect it to in this situation.

I am working in a Foundry project and was hoping to give this plugin a try alongside my current workflow. It looks like my current roadblock is that Hardhat does not support library path remapping, best described in [Issue 2527](https://github.com/NomicFoundation/hardhat/issues/2527). Ideally I would want to point Hardhat to look for libraries in the /lib folder, and then respect the entries in `remappings.txt`.

**Comment by antico5** [comment]
That's the case as of right now. But fortunately, we are working on the next big release that's coming within a few weeks, which gives full support (analysis, navigation, linting, etc) both to "standalone" solidity files and foundry projects as well. That involves supporting remappings, solc version, etc, from foundry projects. 

Separately, we are also about to release a hardhat plugin for giving support to mixed hardhat-foundry projects, which you may be interested in in the future in case you want to use add hardhat tools to your existing project.

Stay tuned!
