### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by babyface001** [NomicFoundation/hardhat-vscode#294]
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
[Error - 6:43:30 PM] Connection to server got closed. Server will not be restarted.

**Comment by kanej** [comment]
Hey @babyface001, can I ask what the steps where that lead up to this error.

Once the error happens, what functionality do you lose, do the warnings and errors disappear or is it all of the extensions functions (navigation, renames, quickfixes etc)?

**Comment by babyface001** [comment]
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
[Trace - 6:59:20 PM] [core:23] Compiling: End (12192ms)
[Trace - 6:59:20 PM] [core:23] Error: Command failed: /Users/baby/Library/Caches/hardhat-nodejs/compilers/wasm/soljson-v0.8.17+commit.8df45f5f.js --standard-json
/bin/sh: /Users/baby/Library/Caches/hardhat-nodejs/compilers/wasm/soljson-v0.8.17+commit.8df45f5f.js: Permission denied

**Comment by babyface001** [comment]
@kanej  I open verbose log and it use js as cmd. and error.

**Comment by babyface001** [comment]
compile in terminal is ok

**Comment by babyface001** [comment]
<img width="469" alt="image" src="https://user-images.githubusercontent.com/34022395/204086088-c252e0a4-dccf-47f5-9f26-4b589e1e3a87.png">

**Comment by kanej** [comment]
And this happens when you open the project? Or when you run the build task?

**Comment by babyface001** [comment]
after this, import auto complete is missing.

**Comment by babyface001** [comment]
yes, open a sol file.

**Comment by babyface001** [comment]
maybe it try to compile it.

**Comment by kanej** [comment]
Okay. This is a bug we will dig into.

I suspect the issue is that the vscode process doesn't have permission on the solc compiler downloaded by hardhat, and that exception kills the language server (so autocomplete and other features stop working.)

**Comment by kanej** [comment]
Are there any special file permissions, or anything around your user that would block permission on: `/Users/baby/Library/Caches/hardhat-nodejs/compilers/wasm/soljson-v0.8.17+commit.8df45f5f.js`?

**Comment by babyface001** [comment]
I run `chmod +x`, but now work, it run js with `/bin/sh`, right?

**Comment by babyface001** [comment]
[Trace - 7:45:40 PM] analyse
[Trace - 7:45:40 PM] [core:1] Building compilation (Hardhat - Cash.sol): Start
[Trace - 7:45:40 PM] [core:1] Building compilation (Hardhat - Cash.sol): End (33ms)
[Trace - 7:45:40 PM] [core:1] Compiling: Start
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
[Trace - 7:45:41 PM] [core:1] Compiling: End (938ms)

**Comment by babyface001** [comment]
analyse service

**Comment by babyface001** [comment]
@kanej 
https://github.com/NomicFoundation/hardhat-vscode/blob/21af73fde3/server/src/services/validation/CompilationService.ts#L25

https://github.com/NomicFoundation/hardhat/blob/080a25a7e188311d7e56366e1dae669db81aa2d7/packages/hardhat-core/src/builtin-tasks/compile.ts#L632

it run native compiler with js compiler path.

**Comment by babyface001** [comment]
`compile:solidity:solc:run` or `compile:solidity:solcjs:run` should be detected.
