### ISSUE TITLE
Generate comments automatically for a function in solidity

### ISSUE THREAD

**Issue by meanking** [NomicFoundation/hardhat-vscode#296]
Hi

I would like to suggest you support the auto-comment generation feature for solidity extension.

For example:
let's assume we have this function.

```
function setAdmin(address _admin, bool _enabled) external onlyOwner {
        _admins[_admin] = _enabled;
        
        emit SetAdminAccess(true);
    }
```
Then I want to have a comment skeleton like this when I write `/** ` and press `enter`.

```
/**
     * @notice
     *
     * @param _admin
     * @param _enabled
     */
```

I think this is possible because you are providing this for javascript/typescript already.

Looking forward to hearing from you.

Best regards,
Meanking

**Comment by kanej** [comment]
That is a great suggestion.

We are focused on vim.coc support right now, but we will be looking generally at how we deal with comments in the new year.
