### ISSUE TITLE
Move formatting to server side

### ISSUE THREAD

**Issue by antico5** [NomicFoundation/hardhat-vscode#300]
Right now we are executing code formatting (prettier/forge fmt) on the client side. We could move that to the server side by implementing the `textDocument/willSaveWaitUntil` method, or the `textDocument/formatting` method (probably VSCode issues the latter when the "format on save" setting is enabled)

**Comment by kanej** [comment]
`vim.coc` supports the format command. So if we add it to the language server, vim gets it as well.
