### ISSUE TITLE
Only analyze project local files on initialization stage

### ISSUE THREAD

**Issue by antico5** [NomicFoundation/hardhat-vscode#302]
Right now we analyze all solidity files found under project folders. That includes libraries as well. A huge speed boost to the initialization stage could be analyzing just the local files (e.g. source paths for hardhat, src/test/script for foundry). 

A useful metric for tracking this is the `indexing` transaction p50-p95 on sentry

**Comment by kanej** [comment]
This would leverage the recursive analysis changes right?

So the process would be something like:

* identify projects
* for each project determine root project solidity files (i.e. `./contracts` for hardhat)
* run analysis to completion for each of those solidity files

Does this require a change in our hardhat and foundry adapters then?

**Comment by kanej** [comment]
For reference, as of 2023-01-02:
* P50: 6.44s
* P95: 15.99s

So worth speeding up.
