### ISSUE TITLE
bug: `abi.encodeCall` is not shown as a suggestion

### ISSUE THREAD

**Issue by mds1** [NomicFoundation/hardhat-vscode#319]
Using v0.6.5 of the extension with Solidity 0.8.17 in a foundry project, and `abi.encodeCall` is not shown as an autocomplete suggestion, even though it's valid and I can use it in the code

<img width="609" alt="image" src="https://user-images.githubusercontent.com/17163988/209021743-9d49bdc2-3f36-4933-a2bc-4ab7ef82ca18.png">

**Comment by kanej** [comment]
Thanks for that @mds1, this bug fix should be out in the next release.

Any other completions problems, we are keen to hear about.
