### ISSUE TITLE
Suppress `Error loading HRE` from telemetry

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-vscode#340]
We handle and display loading errors in the hardhat config, but send the exception on to sentry our telemetry and exception reporting system. We should suppress it from going to sentry, so our telemetry is not full of variants of:

> Error loading HRE: Error: Cannot find module '@nomicfoundation/hardhat-toolbox'

**Comment by antico5** [comment]
Can we set up filter rues on sentry or it's better to have it on the code?

**Comment by kanej** [comment]
> Can we set up filter rules on sentry or it's better to have it on the code?

We can setup up filter rules on sentry, but it goes towards our error quota.

There maybe ways of doing it within the sentry client though.
