### ISSUE TITLE
Assumes Foundry installation location

### ISSUE THREAD

**Issue by frangio** [NomicFoundation/hardhat-vscode#354]
The location of the `forge` executable is assumed to be `~/.foundry/bin/forge` on non-Windows. I think this is the location where `foundryup` installs, but it can also be installed by other means in other locations in the `$PATH`.

```
Error: Command failed: ~/.foundry/bin/forge config --json
/bin/sh: line 1: ~/.foundry/bin/forge: No such file or directory
```

**Comment by antico5** [comment]
Thanks for pointing it out. Initially we were using `forge` directly but had the issue that depending how vscode was launched, that command could be visible or not. A good improvement would be to try to run `forge` directly, then fall back to the default installation directory (current), and then error if neither are found.
