### ISSUE TITLE
URI must contain a scheme

### ISSUE THREAD

**Issue by frangio** [NomicFoundation/hardhat-vscode#355]
I know this isn't yet fully supported but I'm trying to run the server directly with Neovim's built in LSP client.

I'm seeing this error that seems to prevent the server from working at all:

```
URI must contain a scheme: /home/[...]/AccessControl.sol
```

This seems to be triggered by:

```
[TRACE][2023-01-03 17:34:03] .../lua/vim/lsp.lua:1045	"notification"	"textDocument/publishDiagnostics"	{  diagnostics = {},  uri = "/home/[...]/AccessControl.sol"}
```

Neovim seems to expect that the `uri` field will start with `file://` or some other scheme.

**Comment by antico5** [comment]
Good catch. We should be using URIs instead of paths on the `publishDiagnostics` notification. My guess is that both vscode and coc.nvim assume the scheme is file but we should make it explicit to be more compliant with the protocol.
