### ISSUE TITLE
Add instruction for vim users on how to check output logs

### ISSUE THREAD

**Issue by antico5** [NomicFoundation/hardhat-vscode#384]
Since we don't have status items on vim to show project problems, like dependencies not installed or wrong config files, the only clue for finding the problem would be on the language server logs. It's not widely known how to access those, so we may add the instructions for vim users for:
- Checking the server logs by running `:CocCommand workspace.showOutput` -> solidity
- They should run `:CocRestart` after installing dependencies (e.g. openzeppelin contracts)

**Comment by 16rakib16** [comment]
test
