### ISSUE TITLE
excessive CPU usage 

### ISSUE THREAD

**Issue by Amxx** [NomicFoundation/hardhat-vscode#386]
As mentioned in [this tweet](https://twitter.com/Amxx/status/1609865300261863428), I've experienced severe cpu usage. Enabling the extension will cause my laptop fan to spin up, and my battery to drain.

Without any extension
---

![Capture d’écran du 2023-02-02 15-38-48](https://user-images.githubusercontent.com/2432299/216354471-997aec26-f206-43e2-8b46-1739ff0a32b7.png)

With the solidity extension (0.6.9)
---

![Capture d’écran du 2023-02-02 15-39-12](https://user-images.githubusercontent.com/2432299/216354478-b0abcbd5-0661-46ad-a56b-89e539623ea8.png)

Environment
---

![Capture d’écran du 2023-02-02 15-25-38](https://user-images.githubusercontent.com/2432299/216351551-2cd26d2b-c379-4ac2-9724-008a7792e060.png)

Please let me know which command to run to provide more information that might help fix that. I'd love to use this extension, but its currently not realistic in a mobile environment.

**Comment by kanej** [comment]
Hello @Amxx is the repo your working on open source?

**Comment by Amxx** [comment]
My workspace includes 31 folders. I'd say half of them are solidity. And half of that is publicly available.

**Comment by Amxx** [comment]
> or create a workspace by using `Add folder to workspace` and just select the necessary ones.

That is what I did though, I started with an empty workspace and added ~31 folders. Some folder are decently big ... i'll try to close some.

**Comment by antico5** [comment]
@Amxx hi! with PR #395 being merged, at most 1 of your CPUs will be utilized intensively. This may result in the initialization process taking longer but at least it won't grab all the CPUs available when you have a high number of projects open. Please get back to us with any further suggestions or reports!
