### ISSUE TITLE
Fails to install with CocInstall

### ISSUE THREAD

**Issue by amanusk** [NomicFoundation/hardhat-vscode#402]
Trying to install in vim (version 9.0) using `CocInstall @ignored/coc-solidity` I get the error

```
main file out/index.js not found, you may need to build the project.
```

Using node version `18.9.1`

**Comment by amanusk** [comment]
@kanej installation works now. Thanks so much for the prompt response!

I'll hijack this to raise another issue.
The plugin worked for me before, but now I get this error after a few seconds:

```
 Uncaught exception: Header must provide a Content-Length property.
```
 
And non of the functionality works (no jump to def, no autocomplete)

Any tips?

I can open a separate issue for that

**Comment by kanej** [comment]
@amanusk what does the log show, if you run: `:CocCommand workspace.showOutput`

Is the repo your working opensource?

**Comment by amanusk** [comment]
Happens on multiple repos.

Just tried with uniV2 periphery 
https://github.com/Uniswap/v2-periphery.git


```
[Info  - 18:42:12.264] Language server starting
[Info  - 18:42:12.265]   Release: @ignored/coc-solidity@0.6.11
[Info  - 18:42:12.265]   Environment: production
[Info  - 18:42:12.265]   Telemetry Enabled: true
[Info  - 18:42:12.265]   Telemetry Tracking Id: 3a43426d9c...
[Info  - 18:42:12.265]   Workspace Folders:
[Info  - 18:42:12.265]     v2-periphery (file:///home/amanusk/Code/Solidity/v2-periphery)
[Info  - 18:42:12.265] Fetching latest solidity versions
[Info  - 18:42:12.704] Language server ready
[Info  - 18:42:12.962] [indexing] Found projects:
[Info  - 18:42:12.962] [indexing] Scanning workspace folders for sol files
[Info  - 18:42:13.163] [indexing] Scan complete, 42 sol files found
[Info  - 18:42:16.498] [indexing] Analyzing 42 solidity file
```

**Comment by kanej** [comment]
I was able to get the same error but not on the v2-periphery repo. I have opened an issue for it https://github.com/NomicFoundation/hardhat-vscode/issues/407
