### ISSUE TITLE
No completion for special variables 

### ISSUE THREAD

**Issue by MonadeInFlask** [NomicFoundation/hardhat-vscode#406]
It seems that the lsp don't provide completions for global variables such as msg, block. Can this feature be added？

**Comment by antico5** [comment]
Thanks for your feedback! There's already an open issue for this: https://github.com/NomicFoundation/hardhat-vscode/issues/334. We'll address it as soon as possible :)

**Comment by antico5** [comment]
Duplicate of #334

**Comment by MonadeInFlask** [comment]
thank you.

**Comment by kanej** [comment]
I am going to close this as a duplicate of #334.
