### ISSUE TITLE
coc-solidity showing "Header must provide a Content-Length property"

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-vscode#407]
Originally reported by @amanusk in #402: https://github.com/NomicFoundation/hardhat-vscode/issues/402#issuecomment-1442071486

> The plugin worked for me before, but now I get this error after a few seconds:

![image](https://user-images.githubusercontent.com/24030/221152881-61059370-1f83-43c8-bf0d-c3a115c9da28.png)

@amanusk reports it happening on uniV2 periphery: https://github.com/Uniswap/v2-periphery.git

I have seen it happen on the hifi repo: https://github.com/hifi-finance/hifi

I do not have reproduction steps. The analysis completes and hovers and navigation work. Then at some point all actions show the error above.

Opening in vscode doesn't seem to lead to this error. I have not seen it (yet) in nvim on the same repo.

**Comment by kanej** [comment]
Our investigations didn't reveal reproduction steps.

Similar mentions of this error in other coc extensions and in [node language server](https://github.com/microsoft/vscode-languageserver-node) indicate a problem in forming the return message (which should have an initial content length section encoded in ascii).

We have taken two steps based on that theory:

1. Update the version of the language server to pull in any bug fixes
2. Sharpen our use of async when returning message to try and avoid contention on the return connection

Both have been released as part of https://github.com/NomicFoundation/hardhat-vscode/pull/415

**Comment by kanej** [comment]
@amanusk could you try to install the `v0.6.12` version of `@ignored/coc-solidity` to see if the above changes lessens the frequency of the `Content-Length` error?

**Comment by amanusk** [comment]
Tried with the new version.
On uniV2 it does appear to be more stable.
In this example repo the failure appears quite consistently, and a few seconds after opening any file in `contracts`

This does not seem to be the case with vs-code

https://github.com/amanusk/hardhat-vscode-failed

**Comment by kanej** [comment]
> 

Oh thanks for the reproduction repo. We will take a look.

**Comment by kanej** [comment]
Hey @amanusk, we did a release with a fix which we think will resolve the "Header must provide a Content-Length property" issue, version [v0.6.14](https://github.com/NomicFoundation/hardhat-vscode/releases/tag/v0.6.14).

We think that in coc we were using `stdio` to run the language server subprocess, we had assumed we were running the same default as vscode which is `ipc`. The fix swaps coc-solidity to use `ipc`. 

The message problem occurred because any console.logs in the language server output will corrupt the communication over `stdio`, by breaking up the message stream (hence headers not there). We don't console log in the language server, but we hadn't considered console.logs in a hardhat.config, which we load to configure our validation. The repo you provided had console.logs in the hardhat.config, and that is what allowed us to get reproduction steps.

When you have some time, could you try the new version? We will close the issue if you no longer encounter the Header issue. Thanks for all the information on this one, really appreciated.

**Comment by kanej** [comment]
We haven't had any reports of this issue since the `stdio` change. We will reopen if we get a report.
