### ISSUE TITLE
"Couldn't find local hardhat module" when importing a HH+Foundry project to a new Foundry-only project as a dependency

### ISSUE THREAD

**Issue by jameswenzel** [NomicFoundation/hardhat-vscode#446]
I'm working in a foundry project that imports Seaport: https://github.com/jameswenzel/aquaculture

The hardhat extension is unable to recognize remapped imports from Seaport, meaning language features are broken for the files that import from Seaport. 

Viewing any Seaport source file (in `lib/seaport/`) from the module gives a popup reading: `Hardhat project 'seaport' was not able to initialize correctly: Couldn't find local hardhat module. Make sure project dependencies are installed.` in the lower right hand corner.

I'm not sure what that means. Do I have to initialize my own project as a hardhat project just because Seaport uses hardhat? I have hh installed globally via npm, for whatever that's worth.

**Comment by jameswenzel** [comment]
Hm, it _very much was not working_ last night, but today seems fine, even with the error popup. Imports and resolution work as expected. Strange!

**Comment by kamikazebr** [comment]
I also have that error that time in time, i look for some PR or Issue related and found it.

In my case i'm using just Foundry in monorepo. After the messages happens all imports that need the `remappings.txt` file show like error

![image](https://github.com/NomicFoundation/hardhat-vscode/assets/691510/13a73957-a6ed-4c38-99e1-f571ef773e2d)

And the error msg on those is something like

`/fix Source "lib/allo-v2/test/utils/MockERC20.sol" not found: File not found. Searched the following locations: "".`

**Comment by kanej** [comment]
> I also have that error that time in time (intermitent error), i look for some PR or Issue related and found it.
> 
> In my case i'm using just Foundry in monorepo. After the messages happens all imports that need the `remappings.txt` file show like error
> 
> ![image](https://private-user-images.githubusercontent.com/691510/293776986-13a73957-a6ed-4c38-99e1-f571ef773e2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzgwNjgsIm5iZiI6MTcwNDM3Nzc2OCwicGF0aCI6Ii82OTE1MTAvMjkzNzc2OTg2LTEzYTczOTU3LWE2ZWQtNGMzOC05OWUxLWY1NzFlZjc3M2UyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxNDE2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2I1NWM4ZWM0NWVkYzZiYjFjMzM4NTEyNDIzZWM1YzU5YTI3NWJhMzliN2Y2NzljNWFhN2NjM2E0ZjQ5NWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SBpoBDJCCbT1lh0EIZZCIFOx6h1yDB6LRlLvjUwVcZE)
> 
> And the error msg on those is something like
> 
> `/fix Source "lib/allo-v2/test/utils/MockERC20.sol" not found: File not found. Searched the following locations: "".`
> 
> Tried that in VSCode Insiders, VSCodium and VSCode. All the same errors.

Hey @kamikazebr, is the repo you are using open source?
