### ISSUE TITLE
Extension becomes unusably slow for bigger projects

### ISSUE THREAD

**Issue by 0xPhaze** [NomicFoundation/hardhat-vscode#462]
I've noticed a few times that when working in bigger projects, the plugin would just be too slow and not respond. I'm currently working on a personal project of mine, and just recently it suddenly got very slow. After writing a few more tests, the plugin stopped working completely, most notably, because I could not run the formatter anymore. I'm using `forge` as a formatter and can run `forge fmt` in the console without a problem. Changing the formatter also did not help. I was able to use it again after deleting the extension and some lines of code, but it quickly broke down again. If I can trigger this consistently, I'll share the repo.

My specs are:
Mac M2 Max 96GB

**Comment by 0xPhaze** [comment]
Here is where it fails for me: 
https://github.com/0xPhaze/solnum/commit/c592785882507c29b580d1ea8783c7a99e1b6fa5

Basically before the commit, everything is fine, but as soon as I uncomment all that code, it begins getting very slow. From there it depends on how long (sometimes almost instantly, sometimes after messing around a lot; might depend on individual specs), but eventually it just freezes up entirely and I have to disable the extension.

**Comment by 0xPhaze** [comment]
It starts out quite fast for me as well, but then gets to this state.. This is what I see on the language server output when it freezes.

```
[Trace - 7:21:39 PM] Sending request 'textDocument/formatting - (21)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/lain/git/solidity/solnum/test/M32x32.t.sol"
    },
    "options": {
        "tabSize": 4,
        "insertSpaces": true
    }
}
```

I also get this window loading forever until I cancel it.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/103113487/234668174-62120429-8161-4e17-90e6-171d7083a794.png">

Though the language server still seems to be responding. This is the output when I hover. The above ^ window is still there.
```
[Trace - 7:23:35 PM] Sending request 'textDocument/hover - (22)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/lain/git/solidity/solnum/test/M32x32.t.sol"
    },
    "position": {
        "line": 766,
        "character": 4
    }
}


[Trace - 7:23:35 PM] Sending notification '$/cancelRequest'.
Params: {
    "id": 22
}
```

Once I do actually cancel though, I get the following output:

```
[Trace - 7:25:23 PM] Sending notification '$/cancelRequest'.
Params: {
    "id": 21
}


[Trace - 7:25:23 PM] Sending notification 'textDocument/didChange'.
Params: {
    "textDocument": {
        "uri": "file:///Users/lain/git/solidity/solnum/test/M32x32.t.sol",
        "version": 9
    },
    "contentChanges": [
        {
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 0
                }
            },
            "rangeLength": 1,
            "text": ""
        }
    ]
}


[Trace - 7:25:23 PM] Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "file:///Users/lain/git/solidity/solnum/test/M32x32.t.sol"
    }
}


[Trace - 7:25:23 PM] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {
    "changes": [
        {
            "uri": "file:///Users/lain/git/solidity/solnum/test/M32x32.t.sol",
            "type": 2
        }
    ]
}
```

Perhaps the issue is somewhere else? I switched back to Juan Blanco's extension and haven't had any problems at all in this repository.

**Comment by kanej** [comment]
@antico5 taking a look at the foundry.toml there are file permission configurations:

![image](https://user-images.githubusercontent.com/24030/234853113-f6c8920a-c9f5-4c86-ad46-b358a7104407.png)


Could there be a file permission error that blocks within the format call (which is `execSync` for forge), which then blocks other features? Could forge validation actually be the blocking aspect, but it shows up in the formatting call which is now server side?

**Comment by antico5** [comment]
What seems to be happening is that forge fmt is not exiting. Then our server is frozen because we are using execSync for calling it. We can't process other requests while we are waiting for that process. Not even `cancelRequest` requests.

I don't know why forge fmt could not be exiting properly. Perhaps it has to do with how we invoke it and how we send the standard input?

As a potential solution I could suggest switching to async exec for format calls.

**Comment by kanej** [comment]
@antico5 agreed. Are there any blocking calls to forge in validation?

@0xPhaze can you try turning the `formatter` to `none`? This will let us determine if it is just our formatter that has an issue or any use of the foundry cli within the extension in your context. When you get an example of it getting "stuck" are you able to run `forge fmt` and `forge build`?

**Comment by 0xPhaze** [comment]
It's a bit hard for me to test, because this bug isn't easily reproducible. Though I remember that after it was stuck, changing the formatter setting to "none" or "prettier" didn't make a difference.

**Comment by 0xPhaze** [comment]
@kanej It seems to be working well so far. Thanks! Closing this issue.

**Comment by 0xPhaze** [comment]
Hmm, just wanted to leave the note here that it's still quite slow at times. And it just took a few seconds until it displayed this new message when saving/formatting.

<img width="373" alt="image" src="https://github.com/NomicFoundation/hardhat-vscode/assets/103113487/b76556e6-4118-402a-9f8c-877c07a856c5">

At least this time it did not freeze up entirely and I could continue using it afterwards.

**Comment by kanej** [comment]
> Hmm, just wanted to leave the note here that it's still quite slow at times. And it just took a few seconds until it displayed this new message when saving/formatting.
> <img alt="image" width="373" src="https://user-images.githubusercontent.com/103113487/241798085-b76556e6-4118-402a-9f8c-877c07a856c5.png">
> 
> At least this time it did not freeze up entirely and I could continue using it afterwards.

Thanks for the update @0xPhaze, what does the output show for those slowdowns?
