### ISSUE TITLE
import errors on hardhat depending on the root directory

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-vscode#470]
This issue was raised on twitter: https://twitter.com/0xPrimata/status/1651226891871821826

```
build project, in /d/Project/Feature;
import openzeppelin contract;

code . /d/Project 
cd Feature
import error

code . /d/Project/Feature
no import error
```

![image](https://user-images.githubusercontent.com/24030/234826400-4a4e6c92-ad0c-4b94-a7c1-3adbea7358bb.png)

**Comment by antico5** [comment]
I tried to reproduce this on linux and windows and wasn't able to. Even included whitespaces on the directories to try to replicate. I also tried making the root directory a hardhat project itself (has a hardhat config file, contracts, etc), and even then the sub-project works properly.

**Comment by kanej** [comment]
I will ping on twitter to see if the repo is open source.

**Comment by kanej** [comment]
Closing as no response.
