### ISSUE TITLE
False positive unused import when using named import syntax

### ISSUE THREAD

**Issue by PaulRBerg** [NomicFoundation/hardhat-vscode#503]
[It appears](https://twitter.com/PaulRBerg/status/1670018712236072960) that a recent version of Hardhat VSCode has added support for detecting unused imports (which I think is powered by [solhint-community](https://github.com/solhint-community/solhint-community)).

The problem is that this feature does not work with imports of this form:

```solidity
import { Foo as Bar } from "../src/Foo.sol";
```

Even if `Bar` is used in the code, the extension reports that it is not used:

<img width="369" alt="Screenshot 2023-06-18 at 4 16 17 PM" src="https://github.com/NomicFoundation/hardhat-vscode/assets/8782666/c720f43b-3259-4981-8ff4-46165bdd2788">

To reproduce this:

- Start from my [Foundry template](https://github.com/PaulRBerg/foundry-template)
- Go to `test/Foo.t.sol`
- Replace the `Foo` import as I have shown above
- Replace all uses of `Foo` by `Bar`

**Comment by kanej** [comment]
We have not added an `unused import` feature. Is this coming in from another extension?

I couldn't reproduce based on your template.

**Comment by PaulRBerg** [comment]
Oh wow - so I was wrong in my [tweet](https://twitter.com/PaulRBerg/status/1670018712236072960)!

It looks like this "Unused import" feature is due to [vscode-solidity-inspector](https://github.com/PraneshASP/vscode-solidity-inspector).

Sorry for the false positive.

**Comment by kanej** [comment]
It is such a good idea, I will add it as an feature request.
