### ISSUE TITLE
Import statements not recognized in projects in symlinked folders

### ISSUE THREAD

**Issue by TomiOhl** [NomicFoundation/hardhat-vscode#512]
There is no auto-completion for import statements and clicking on the does not navigate to the source file.
![image](https://github.com/NomicFoundation/hardhat-vscode/assets/6696659/354c59cd-02cb-4acc-aeb1-4639e43e2c24)
Happens with both npm and local imports. Tried in different projects.
Note that navigation between files works when I reference other contracts elsewhere in the code, just not when clicking on the import statements themselves.

hardhat-vscode 0.7.3
vscode 1.80.2
node v18.16.0
elementary OS 7 (based on Ubuntu 22.04)

**Comment by kanej** [comment]
Hey @TomiOhl, is this running in a Hardhat project or Foundry.

Is the repo open source to help me reproduce?

**Comment by TomiOhl** [comment]
It's basically any project that I open. I'm using hardhat.
An example: https://github.com/agoraxyz/guild-pin-contract

**Comment by TomiOhl** [comment]
Did an experiment: normally the projects I work on are in a folder that's symlinked to my home folder from another partition. However, after copying a project to my home folder directly, the issue no longer persists. Hence I updated the title, too.
Note: [Juan Blanco's Solidity extension](https://github.com/juanfranblanco/vscode-solidity) supports symlinked folders, too

**Comment by kanej** [comment]
Hey @TomiOhl. This is known issue: https://github.com/NomicFoundation/hardhat-vscode/issues/270

We have an issue with our Hardhat analysis (which leverages node process spawning and that doesn't work well with symlinks).

I am going to close this issue in preference for #270.
