### ISSUE TITLE
interface error (computing)

### ISSUE THREAD

**Issue by SolExpDB** [NomicFoundation/hardhat-vscode#513]
There are some smart contract functions that do not have a return value and defining the interface will result in an error. There are also cases where the same function name has a different return value.
<img width="1409" alt="image" src="https://github.com/NomicFoundation/hardhat-vscode/assets/138878504/54bf42f0-ff24-4a0a-9fa7-54849caa37c8">
<img width="984" alt="image" src="https://github.com/NomicFoundation/hardhat-vscode/assets/138878504/80672eca-076e-4697-8c13-0d840f6132a8">

**Comment by kanej** [comment]
I am not following @SolExpDB. Do you think the solidity compiler error is wrong or that the vscode extension has autocompleted or quickfixed in a way that generates a compiler error?

**Comment by SolExpDB** [comment]
@kanej I think this is a bug in the vscode extension, some functions with the same name and arguments but different return values are not buggy. But there are some functions that give an error

**Comment by kanej** [comment]
Solidity error *1686* is coming from solc, this issue is part of the Solidity language.
