### ISSUE TITLE
Autocompletion doesn't work if there's a line without the ; in the file

### ISSUE THREAD

**Issue by C0D3O** [NomicFoundation/hardhat-vscode#517]
doesn't  work
![image](https://github.com/NomicFoundation/hardhat-vscode/assets/75484297/c1068204-6354-480f-860c-41b59654ee01)
works
![image](https://github.com/NomicFoundation/hardhat-vscode/assets/75484297/1f7f56ad-6c48-45f5-9f67-352bb3a16b68)

**Comment by kanej** [comment]
@moneyDev1111 thanks for reporting this. In general our completions are degraded if there are syntax errors in the file. Our current parser and binding analysis isn't robust to syntax errors.

This is a hard problem and Nomic's [Slang team](https://github.com/NomicFoundation/slang) are building out the parser and compiler tooling we need to address it.

**Comment by kanej** [comment]
Closing with preference https://github.com/NomicFoundation/hardhat-vscode/issues/517.
