### ISSUE TITLE
This is just impossible to work with

### ISSUE THREAD

**Issue by C0D3O** [NomicFoundation/hardhat-vscode#519]
https://github.com/NomicFoundation/hardhat-vscode/assets/75484297/32afab05-5a39-4e1f-acf7-600fb82aa998

**Comment by kanej** [comment]
Is the extension reporting an incorrect compiler error on first load of the file? Or are there steps that lead up to it being out of sync?

**Comment by moneyDev1111** [comment]
no, no compiler errors. I just install the extension and this is how it works by default. Still it's the best there is, unfortunately ahaha

**Comment by moneyDev1111** [comment]
I will try to debug it with a blank project

**Comment by moneyDev1111** [comment]
everything hapepns because of the array of compilers on the config.. let me debug it further

**Comment by moneyDev1111** [comment]
it seems like that the problem is with the .... vscode itself? like if there's a big project and you make many fast changes to a file, it seems like it just can't keep up with the current state.......

**Comment by moneyDev1111** [comment]
no, not really...

**Comment by moneyDev1111** [comment]
https://github.com/NomicFoundation/hardhat-vscode/assets/75484297/a3a20c56-8af6-4311-89b6-0cdc3c3115ae

I removed everything from the config except the compliler version and it behaves the same

**Comment by moneyDev1111** [comment]
@kanej seem like I found what's causing the issue!:) hopefully

**Comment by moneyDev1111** [comment]
it's not about the hardhat config.... I can't find the reason, no matter what I try, it still fails to be in sync...

**Comment by fvictorio** [comment]
Closing this for now. Happy to re-open if we have reproduction steps.
