### ISSUE TITLE
Computer Getting Wrecked: 41 `nomicfoundation.hardhat-solidity-0.7.3` Workers Persist After VSCode is Closed

### ISSUE THREAD

**Issue by amarpatel** [NomicFoundation/hardhat-vscode#525]
### I had 1 instance of VSCode running with 2 windows open, then I `cmd+q`'d both to quit VSCode.  In Activity Monitor, it continued to show `Code Helper` processes running:

![Untitled](https://github.com/NomicFoundation/hardhat-vscode/assets/5858247/ea171d16-e85a-49c0-b6a1-1852b6dac0a1)

#### NOTE: The other lines isolate the extension path and remove the PID from the results

<img width="530" alt="Screenshot 2023-10-27 at 8 57 16 AM" src="https://github.com/NomicFoundation/hardhat-vscode/assets/5858247/08ae0fe5-1e4d-43ce-947d-b1100316ed29">

### This is the second time this has happened this week.  On Monday (4 days ago), I captured this process while VSCode was running: 

<img width="741" alt="image" src="https://github.com/NomicFoundation/hardhat-vscode/assets/5858247/c7357e85-7e0e-4d2d-a512-49557c4f20a6">

### Computer specs:
- Apple MBP 16" 2021
- M1 Max
- 64GB memory
- Ventura 13.5.2

### VSCode:
Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:57:32.750Z (2 wks ago)

**Comment by amarpatel** [comment]
cc @alcuadrado

**Comment by kanej** [comment]
Hey @amarpatel is the repo you were running in open source, to help me reproduce?

Does this happen every time you open the workspace and quit? Or is it intermittent?

**Comment by kanej** [comment]
Closing as we have had no further reports. We will reopen if we get more information.
