### ISSUE TITLE
hybrid foundry + hardhat is missing go to navigation when used with `hardhat-foundry` plugin

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-vscode#543]
Reported on discord: https://discord.com/channels/750408878008827925/951537942239797338/1207246837237420032

> Hello, i'm trying to set up a hybrid hardhat/foundry project but stuff like go to definition quits working when foundry is set up. When i comment out hardhat-foundry in hardhat.config.ts everything works again... Is there any solution to this?

A hybrid Hardhat + Foundry should support go to navigation and other features dependent on static analysis of the project; particularly if used with the `hardhat-foundry` plugin on the Hardhat side.

## Reproduction steps

1. Init a new Hardhat project
2. Initialize foundry
3. Add hardhat-foundry as a plugin, confirm compilation works from HH
4. Attempt navigation within the vscode extension (it should not work). Comment out the `hardhat-foundry` plugin. Restart vscode and attempt navigation (it should work)

See the minimal reproduction in this repo: https://github.com/69ren/Hardhat-Foundry-test

In the vscode extension we differentiate between HH projects, Foundry projects, HH + Foundry hybrid projects. We should investigate whether the presence of `hardhat-foundry` is being taken into account in the project calculation i.e. is a hybrid HH + foundry project with `hardhat-foundry` really included better approached as a pure HH project from the extensions point of view for static analysis?.

**Comment by fvictorio** [comment]
Is this a duplicate of https://github.com/NomicFoundation/hardhat-vscode/issues/571?

**Comment by kanej** [comment]
Agreed, closing in favour of #571
