### ISSUE TITLE
ramp up slang features for vscode users

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/hardhat-vscode#546]
- [x] Ship a new extension version, [including the Slang binaries](https://github.com/NomicFoundation/hardhat-vscode/blob/development/.vscodeignore).
- [x] Ramping up `flags.json` settings introduced in #523 to 100% gradually.
- [x] Observing any errors/telemetry issues in Sentry, and report/fix as-needed.
- [x] Report any Slang issues, and integrate fixes as they are released.
- [x] Remove the `isSlangSupported` utility, and ship an extension that unconditionally enables the features.
- [x] Remove `flags.json` and clean up the code that uses it: https://github.com/NomicFoundation/hardhat-vscode/pull/598

cc @Xanewok as the extension was recently upgraded to the latest Slang version in #545

**Comment by fvictorio** [comment]
@OmarTawfik should we close this one?

**Comment by OmarTawfik** [comment]
O

**Comment by OmarTawfik** [comment]
Looking into this, I suggest keeping it open until we eventually remove the `flags.json` usage and release a new version.
