### ISSUE TITLE
Support for Solidity code snippets in Markdown

### ISSUE THREAD

**Issue by PaulRBerg** [NomicFoundation/hardhat-vscode#572]
See context on Twitter: [Is there any VSCode extension that can enable syntax highlighting for Solidity code blocks in Markdown?
](https://x.com/PaulRBerg/status/1790391657797472580)

It appears that Juan Blanco's [extension](https://github.com/juanfranblanco/vscode-solidity) offers support for Solidity code snippets in Markdown.

**Comment by kanej** [comment]
This seems to be done with an injection grammar: https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars

We should see if there are any guidelines for the standard markdown extension.

**Comment by michaeltomasik** [comment]
Hey @kanej & @PaulRBerg just made a PR for this issue https://github.com/NomicFoundation/hardhat-vscode/pull/575

**Comment by kanej** [comment]
Released as part of `v0.8.4`

**Comment by PaulRBerg** [comment]
I am using v0.8.6, and I'm still not able to see highlighted Solidity code.

<img width="450" alt="SCR-20241120-mpvl" src="https://github.com/user-attachments/assets/1560df85-21e7-4f45-8397-fe77af3ae1a2">

**Comment by kanej** [comment]
> Released as part of `v0.8.4`

Thanks for the report, this is a bug in our release scripts (the extra syntax file wasn't being copied). I have put [together a fix](https://github.com/NomicFoundation/hardhat-vscode/pull/616) and will ping here when it goes out in the next release (likely Monday).

**Comment by kanej** [comment]
> > Released as part of `v0.8.4`
> 
> Thanks for the report, this is a bug in our release scripts (the extra syntax file wasn't being copied). I have put [together a fix](https://github.com/NomicFoundation/hardhat-vscode/pull/616) and will ping here when it goes out in the next release (likely Monday).

@PaulRBerg, that is `v0.8.7` released with the build script changes, you should be able to see Solidity highlighting in Markdown files:

https://github.com/NomicFoundation/hardhat-vscode/releases/tag/v0.8.7
