### ISSUE TITLE
Hovering variables/functions doesn't show anything

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-vscode#62]
In the language server spec this feature is referred to as `hover`:

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_hover

You can see it in action in typescript:

![image](https://user-images.githubusercontent.com/24030/152982225-3e029f25-4a60-44f0-aec3-95f0ef16c060.png)

We may want to split out different syntactic elements and implement them based on ease/speed to feature:

* variables
* functions
* contracts

**Comment by the-vampiire** [comment]
I am still not getting anything on hover for anything imported. Turning on verbose logging setting it says "no results returned". 

For example (I’ll grab a screencap if it helps) but basically:
1. Using `Counters for Counters.<Co…>` this does not recognize the Counter struct (it offers `Counters` or `Context`)
2. Counters.Counter private _ids;

_ids isn’t recognized as a Counter nor are any of its Counters methods displayed when used in functions. 

I posted about this on discord but haven't heard how to get it working. Any advice?

**Comment by the-vampiire** [comment]
Interestingly it does recognize Counters (in the using statement). If I hover over it I get the Counters contract info and with cmd click can navigate to it. But after that point nothing else is hoverable or recognized for intellisense
