### ISSUE TITLE
No validation until first HH compile

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-vscode#81]
The inline validation (showing compiler warnings and errors) will silently fail on a new hardhat project where no compile has ever been run.

My assumption is that we will fail to run the validation job until a compiler has been downloaded.

A similar problem can happen if you copy in a contract with a version pragma that hasn't been seen before.

## Approaches

1. Provide a better warning to the vscode ui that the compiler isn't available
2. Ideally auto-download the needed compiler

**Comment by alcuadrado** [comment]
I think this is no longer present

**Comment by kanej** [comment]
We haven't had a report since feb, and both the suggestions above are now in place. So I will close.
